POST https://api.trakt.tv/oauth/device/code?client_id=
###

POST https://api.trakt.tv/oauth/token?code=&client_id=&client_secret=&redirect_uri=&grant_type=authorization_code

###

/*
Contenido:
{
  "access_token": "6dc9ab5adde21031972999c74967885f8377f3b6077cc7e995b499f3a1587872",
  "token_type": "Bearer",
  "expires_in": 7889237, // Seconds
  "refresh_token": "3b973a66becee3e618f6d9559b1435452ba0370d830d3dc7f20782e96b3c1da3",
  "scope": "public",
  "created_at": 1689243127
}

*/

GET https://api.trakt.tv/sync/watched/shows
Content-Type: application/json
Authorization: Bearer
trakt-api-version: 2
trakt-api-key: 

###

GET https://api.trakt.tv/sync/history/shows
Content-Type: application/json
Authorization: Bearer 
trakt-api-version: 2
trakt-api-key: 
X-Pagination-Page: 1
X-Pagination-Limit: 10
X-Pagination-Page-Count: 10
X-Pagination-Item-Count: 100

###